# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_uartlite_0_0/top_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_uartlite_0_0 || ORIG_REF_NAME==top_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_smc_0/top_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_smc_0 || ORIG_REF_NAME==top_axi_smc_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_ps7_0_50M_0/top_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_ps7_0_50M_0 || ORIG_REF_NAME==top_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_iic_0_0/top_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_iic_0_0 || ORIG_REF_NAME==top_axi_iic_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_quad_spi_0_0/top_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_quad_spi_0_0 || ORIG_REF_NAME==top_axi_quad_spi_0_0} -quiet] -quiet

# XDC: c:/enosim/IMS/project_1/project_1.gen/sources_1/bd/top/top_ooc.xdc
